definitions:
  model.Customer:
    properties:
      created_at:
        example: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
        type: string
      email:
        example: johndoe@mail.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: John Doe
        type: string
    type: object
info:
  contact: {}
  title: Simple Payment API
paths:
  /api/customers:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
      summary: Get all customers
    post:
      responses:
        "200":
          description: OK
      summary: Create new customer
  /api/customers/{id}:
    delete:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
      summary: Delete customer by ID
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
      summary: Get customer by ID
  /api/customers/id:
    put:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
      summary: Update customer by ID
swagger: "2.0"
